spring:
  profiles:
    default: local
  application:
    name: cafe-de-barrio-backend

  jpa:
    open-in-view: false

  web:
    error:
      include-message: always
      include-binding-errors: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

server:
  port: 8080
